#!/bin/bash

sudo apt-get update -y && sudo apt-get upgrade -y;
sudo apt-get install -y curl \
    git \
    unzip \
    xz-utils \
    zip \
    libglu1-mesa \
    libc6:amd64 \
    libstdc++6:amd64 \
    libbz2-1.0:amd64 \
    libncurses5:amd64 \
    libc6:i386 \
    libncurses5:i386 \
    libstdc++6:i386 \
    lib32z1 \
    libbz2-1.0:i386