#!/bin/bash

sudo apt update
sudo apt install build-essential \
    libssl-dev \
    zlib1g-dev \
    libbz2-dev \
    libreadline-dev \
    libsqlite3-dev \
    curl \
    git \
    libncursesw5-dev \
    xz-utils \
    tk-dev \
    libxml2-dev \
    libxmlsec1-dev \
    libffi-dev \
    liblzma-dev

curl https://pyenv.run | bash

lines=(
    'export PYENV_ROOT="$HOME/.pyenv"'
    '[[ -d $PYENV_ROOT/bin ]] && export PATH="$PYENV_ROOT/bin:$PATH"'
    'eval "$(pyenv init -)"'
)

for line in "${lines[@]}"
do
    if ! grep -qxF "$line" ~/.bashrc
    then
        echo "$line" >> ~/.bashrc
    fi
done